language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_install:
  - phpenv config-rm xdebug.ini
  
install:
  - composer install --no-progress --prefer-dist

script:
  - composer run-script tester

jobs:
  include:
    - stage: Test Coverage
      php: 7.1
      script:
        - composer run-script coverage
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar -c tests/.coveralls.yml

  allow_failures:
    - stage: Test Coverage

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done